version: '3.4'

services:

  nginx-cars:
    build: ./nginx
    container_name: nginx-cars
    restart: always
    ports:
      - "80:80"

  database-cars:
    image: mongo
    container_name: database-cars
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    expose:
      - 27017
    ports:
      - "27017:27017"


  api-cars:
    build: ./app
    container_name: api-cars
    expose:
      - 80
